/**
 * S5A Render Test — Möbius Close, First Half
 * ────────────────────────────────────────────
 * Generates the first 4 seconds of S5: sustaining ignition residual state.
 * Seeded from S4's final frame — continues from the ignition threshold crossing.
 *
 * LE-003 finding: A single Runway generation cannot execute a hard state reset
 * (ignition → cold void). S5 is split into two 4-second generations stitched
 * in editorial. This script handles the first half (S5A).
 *
 * S5A: ignition zone stable and self-sustaining — the residual energy state.
 *      Not expanding (that was S4). Held. Crimson present. Gold traces.
 *      Crystal structure has completed its transformation. Energy held.
 *
 * S5B: handled by render-s5b-test.ts (cold surface, S1 register).
 *
 * After both complete, stitch with:
 *   ffmpeg -i output/NDCH_017_S5A_test.mp4 -i output/NDCH_017_S5B_test.mp4 \
 *     -filter_complex "[0:v][1:v]concat=n=2:v=1:a=0" \
 *     output/NDCH_017_S5_stitched.mp4
 *
 * Usage:
 *   tsx --env-file=.env render-s5a-test.ts
 *
 * Required env:
 *   RUNWAY_API_KEY
 *
 * Output:
 *   ./output/NDCH_017_S5A_test.mp4
 *   ./output/s5a_frames/frame_01.png … frame_05.png
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve }                                        from 'node:path';
import { execSync }                                             from 'node:child_process';

const RUNWAY_API_KEY = process.env.RUNWAY_API_KEY;
if (!RUNWAY_API_KEY) {
  console.error('RUNWAY_API_KEY is not set.');
  process.exit(1);
}

const S4_SEED_FRAME = resolve('./output/s4_frames/frame_05.png');
const OUTPUT_DIR    = resolve('./output');
const FRAMES_DIR    = resolve('./output/s5a_frames');
const OUTPUT_PATH   = join(OUTPUT_DIR, 'NDCH_017_S5A_test.mp4');
const POLL_INTERVAL = 10_000;
const TIMEOUT_MS    = 600_000;

const RUNWAY_BASE    = 'https://api.dev.runwayml.com';
const RUNWAY_VERSION = '2024-11-06';

// S5A prompt v3: positive-crowding architecture — describe inevitable physical reality
// Principle: desired physics crowds out unwanted symbolism rather than blacklisting symbols
// Structure: Purpose → Physical state → Composition → Geometry → Camera → Palette → Minimal negation
const S5A_PROMPT = [
  'Physical evidence of a completed ignition threshold preserved inside fractured crystalline material,',
  'viewed as forensic residue rather than an object.',
  'The interface between two fractured crystalline surfaces remains the compositional subject.',
  'Irregular asymmetric fracture topology generated by physical stress with no dominant axis of symmetry.',
  'Crimson #DC143C permanently embedded within fractured planes where threshold crossing occurred.',
  'Cream #F5F2EB remains at untouched regions.',
  'Gold #C6A94F telemetry fractures follow broken edges only.',
  'Pure void #1A1A1A background.',
  'Camera locked and observational.',
  'Motion limited to subtle internal shimmer within crystal planes.',
  'Composition reads as material evidence of physical transformation rather than symbolic geometry, ornament, or decorative design.',
].join(' ');

type RunwayTask       = { id: string };
type RunwayTaskStatus = { status: string; output?: string[]; failure?: string };

function headers(): Record<string, string> {
  return {
    'Authorization':    `Bearer ${RUNWAY_API_KEY}`,
    'X-Runway-Version': RUNWAY_VERSION,
    'Content-Type':     'application/json',
  };
}

async function submit(): Promise<string> {
  if (!existsSync(S4_SEED_FRAME)) {
    throw new Error(`S4 seed frame not found: ${S4_SEED_FRAME}\nRun render-s4-test.ts first.`);
  }

  const seedB64 = readFileSync(S4_SEED_FRAME).toString('base64');
  const promptImage = `data:image/png;base64,${seedB64}`;

  console.log('\n[1/3] Submitting S5A to Runway Gen-4.5...');
  console.log('      seed: S4 final frame (output/s4_frames/frame_05.png)');
  console.log(`      prompt (${S5A_PROMPT.length} chars): ${S5A_PROMPT.slice(0, 80)}...`);
  console.log('      duration: 5s | model: gen4.5 | ratio: 720:1280');

  const res = await fetch(`${RUNWAY_BASE}/v1/text_to_video`, {
    method:  'POST',
    headers: headers(),
    body:    JSON.stringify({
      promptText:  S5A_PROMPT,
      promptImage,
      model:    'gen4.5',
      ratio:    '720:1280',
      duration: 5,
    }),
  });

  if (!res.ok) throw new Error(`Runway submission failed: ${res.status}\n${await res.text()}`);
  const { id } = await res.json() as RunwayTask;
  console.log(`      task id: ${id}`);
  return id;
}

async function poll(taskId: string): Promise<string> {
  console.log('[2/3] Polling...');
  const deadline = Date.now() + TIMEOUT_MS;
  while (Date.now() < deadline) {
    await new Promise(r => setTimeout(r, POLL_INTERVAL));
    const res = await fetch(`${RUNWAY_BASE}/v1/tasks/${taskId}`, { headers: headers() });
    if (!res.ok) throw new Error(`Poll failed: ${res.status}`);
    const task = await res.json() as RunwayTaskStatus;
    console.log(`      status: ${task.status}`);
    if (task.status === 'SUCCEEDED' && task.output?.length) return task.output[0];
    if (task.status === 'FAILED') throw new Error(`Task failed: ${task.failure}`);
  }
  throw new Error('Timeout');
}

async function download(url: string): Promise<void> {
  console.log('[3/3] Downloading...');
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Download failed: ${res.status}`);
  writeFileSync(OUTPUT_PATH, Buffer.from(await res.arrayBuffer()));
  console.log(`      saved: ${OUTPUT_PATH}`);
}

function extractFrames(): void {
  mkdirSync(FRAMES_DIR, { recursive: true });
  try {
    execSync(
      `ffmpeg -y -i "${OUTPUT_PATH}" -vf "select='eq(n,0)+eq(n,15)+eq(n,30)+eq(n,45)+eq(n,59)'" -vsync vfr "${FRAMES_DIR}/frame_%02d.png"`,
      { stdio: 'pipe' }
    );
    console.log(`      frames: ${FRAMES_DIR}`);
  } catch { console.warn('      FFmpeg extraction failed — extract manually'); }
}

async function main(): Promise<void> {
  console.log('\n=== NDCH_017 S5A — SUSTAINING IGNITION (first half) ===\n');
  console.log('LE-003: Split-generation stitch. This is S5A — 5s from S4 state.');
  console.log('Run render-s5b-test.ts after this to generate S5B (cold surface).\n');

  const id  = await submit();
  const url = await poll(id);
  await download(url);
  extractFrames();

  console.log('\n─────────────────────────────────');
  console.log('S5A VALIDATION');
  console.log('─────────────────────────────────');
  console.log('  [ ] Crimson still present — ignition state held, not expanding');
  console.log('  [ ] Gold traces visible — temperature mapped, stable');
  console.log('  [ ] Camera static or very minimal drift');
  console.log('  [ ] No new symbolism introduced');
  console.log('  [ ] Visually continuous from S4\'s final frame');
  console.log('');
  console.log('If S5A looks right: run render-s5b-test.ts');
  console.log('Then stitch:');
  console.log('  ffmpeg -i output/NDCH_017_S5A_test.mp4 -i output/NDCH_017_S5B_test.mp4 \\');
  console.log('    -filter_complex "[0:v][1:v]concat=n=2:v=1:a=0" \\');
  console.log('    output/NDCH_017_S5_stitched.mp4');
}

main().catch(err => { console.error('\n[ERROR]', (err as Error).message); process.exit(1); });
